language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew :core:jacocoReport --stacktrace

after_success:
  - codecov

notifications:
  email:
    on_failure: change